in travis unittest fail because cwd is missing
In travis all the algebra unittest fail with
AttributeError: 'TestDataContainerAlgebra' object has no attribute 'cwd',
although all inherited classes do have it.